### ISSUE TITLE
File Names cleanup

### ISSUE THREAD

**Issue by ashipaek0** [mwlistscom/getvod#3]
Thank you for getvod.  its a life saver and much appreciated.

Please could you tell me how to get sanitized file names.
When i run getvod i end up with file names that look like this:

EN__National_Lampoon_s_European_Vacation_(1985)EN__National_Lampoon_s_European_Vacation_(1985).strm

Whilst i do not mind the underscores (Unix file names and all), i would very much like to remove the EN__ prefix

I have tried adding that to the

$lefttrim = "EN__";
and even the
$remove[] = "EN__";

but it appears that only produces :

EN_-_National_Lampoon_s_European_Vacation_(1985).strm.

Kindly help me with directions on how to get my files to look like:

`National_Lampoon_s_European_Vacation_(1985).strm`

**Comment by mwlistscom** [comment]
This is probably the issue  - 

  if ($lefttrim != null) { // leave as null and nothing gets removed

change to:

 if ($lefttrim != "") { // leave as null and nothing gets removed

The file underscore is here:

   $file = str_replace(' ', '_', $key->tvg_name);

Just change to: 

//   $file = str_replace(' ', '_', $key->tvg_name);

Some like the underscore because it's easier to deal with in Windows.  

-Jules

**Comment by mwlistscom** [comment]
oh nm, you tried that lefttrim -- let me reproduce and get back to you.

**Comment by mwlistscom** [comment]
If not I'll repro and fix it this weekend.

**Comment by mwlistscom** [comment]
We released a new Repository that works on multiple OS that's easier to maintian. 

https://github.com/mwlistscom/GetSTRM/releases/tag/v1.0.2

There are no plans to update GetVOD going forward
